/**
 * Single Contribution API
 *
 * GET /api/contributions/[id] - Get a single contribution by ID
 */

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import type {
  InlineContribution,
  ContributionContext,
  ContributionReferences,
} from "@/lib/types";

interface RouteParams {
  params: Promise<{ id: string }>;
}

/**
 * Get a single contribution by ID.
 */
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;

    if (!id) {
      return NextResponse.json(
        { error: "Contribution ID is required" },
        { status: 400 }
      );
    }

    const contribution = await prisma.inlineContribution.findUnique({
      where: { id },
      include: {
        linksFrom: true,
        linksTo: true,
      },
    });

    if (!contribution) {
      return NextResponse.json(
        { error: "Contribution not found" },
        { status: 404 }
      );
    }

    // Transform links to API format
    const linksFromFormatted = contribution.linksFrom.map((link) => ({
      id: link.id,
      fromContributionId: link.fromContributionId,
      toContributionId: link.toContributionId,
      linkType: link.linkType,
      autoGenerated: link.autoGenerated,
      confidenceScore: link.confidenceScore,
      createdAt: link.createdAt.toISOString(),
    }));

    const linksToFormatted = contribution.linksTo.map((link) => ({
      id: link.id,
      fromContributionId: link.fromContributionId,
      toContributionId: link.toContributionId,
      linkType: link.linkType,
      autoGenerated: link.autoGenerated,
      confidenceScore: link.confidenceScore,
      createdAt: link.createdAt.toISOString(),
    }));

    // Transform to API response format
    const response = {
      id: contribution.id,
      sessionId: contribution.sessionId,
      userId: contribution.userId,
      problemId: contribution.problemId,
      command: contribution.command,
      subcommand: contribution.subcommand,
      content: contribution.content,
      timestamp: contribution.timestamp.toISOString(),
      timeSinceStart: contribution.timeSinceStart ?? undefined,
      currentAttempt: contribution.currentAttempt ?? undefined,
      context: contribution.context as unknown as ContributionContext,
      references: contribution.references as unknown as ContributionReferences | undefined,
      suggestedCategory: contribution.suggestedCategory ?? undefined,
      relatedPattern: contribution.relatedPattern ?? undefined,
      relatedInvariant: contribution.relatedInvariant ?? undefined,
      helpfulVotes: contribution.helpfulVotes,
      usedInGuidance: contribution.usedInGuidance,
      createdAt: contribution.createdAt.toISOString(),
      updatedAt: contribution.updatedAt.toISOString(),
      linksFrom: linksFromFormatted,
      linksTo: linksToFormatted,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error("Failed to get contribution:", error);
    return NextResponse.json(
      { error: "Failed to get contribution" },
      { status: 500 }
    );
  }
}
